### ISSUE TITLE
How to track performance issues in this lib?

### ISSUE THREAD

**Issue by SilverioMiranda** [microsoft/kiota-serialization-json-dotnet#87]
Hi, i have a large json taking 2+ secs to GET/PATCH/POST using kiota and <50ms with default httpclient+MethodAsJsonAsync<>

Can someone give example how to track performance issues so i can do my research and find exactly where it is?

Framework version: .NET 7 inside blazor server
OS: Linux and Windows
Using latest versions of kiota libraries

**Comment by baywet** [comment]
Thanks for reaching out and for your patience.
We implemented upper open telemetry for tracing.
So you could use that to identify whether the problem comes from the serialization or from something else.
The alternative would be to implement benchmark tests for this repository. Something we have meant to do but never got time to.
Alternatively, you could implement a proxy design pattern with the serialization writer interface to collect the precise metrics of each method.
I hope this helps.

**Comment by SilverioMiranda** [comment]
Thank you, @baywet, for the response. I lost track of this question and only now saw it, after receiving an email from the GitHub policy service.

The issue has been resolved in a newer version of Kiota. I can't specify which one, as I always update to the latest version available and don't monitor the test runs. However, I recently noticed that a specific test now takes only 50ms, compared to the previous 2000ms+.
